Algoritmo "Contarde1a10Para"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/05/2018
Var
// Seção de Declarações das variáveis 
  C: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Para C <- 1 ate 10 passo 3 faca
     Escreval(C)
  FimPara
Fimalgoritmo