Algoritmo "Primeiro"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Walmor Amorim dos Santos
// Data atual  : 02/05/2018
Var
// Seção de Declarações das variáveis 
 msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 msg <- "Ola, mundo!"
 Escreval("Mensagem...: ", msg)

Fimalgoritmo