Algoritmo "SalarioFunc"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/05/2018
Var
// Seção de Declarações das variáveis 
   Sal_Atual, Sal_Novo: Real
   Dep: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreva("Informe valor da



Fimalgoritmo